In [56]:
import pandas as pd
import numpy as np

In [57]:
pd.__version__

'1.0.5'

In [58]:
np.__version__

'1.19.1'

In [59]:
data = pd.read_csv("car_data.csv")

In [60]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [61]:
## What's the average price of BMW cars in the dataset?

data[data['Make']=='BMW']['MSRP'].mean()

61546.76347305389

In [62]:
## Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

data.loc[(data['Year']>=2015) & (data['Engine HP'].isna()==True)]

Make        Model  Year                  Engine Fuel Type  \
539            FIAT         500e  2015                          electric   
540            FIAT         500e  2016                          electric   
541            FIAT         500e  2017                          electric   
2905        Lincoln  Continental  2017    premium unleaded (recommended)   
2906        Lincoln  Continental  2017    premium unleaded (recommended)   
2907        Lincoln  Continental  2017    premium unleaded (recommended)   
2908        Lincoln  Continental  2017    premium unleaded (recommended)   
4203           Ford       Escape  2017                  regular unleaded   
4204           Ford       Escape  2017                  regular unleaded   
4205           Ford       Escape  2017                  regular unleaded   
4206           Ford       Escape  2017                  regular unleaded   
4785           Ford        Focus  2015                          electric   
4789           Ford        Focus  2016                          electric   
4798           Ford        Focus  2017                          electric   
5825      Chevrolet       Impala  2015  flex-fuel (unleaded/natural gas)   
5830      Chevrolet       Impala  2015  flex-fuel (unleaded/natural gas)   
5831      Chevrolet       Impala  2016  flex-fuel (unleaded/natural gas)   
5833      Chevrolet       Impala  2016  flex-fuel (unleaded/natural gas)   
5839      Chevrolet       Impala  2017  flex-fuel (unleaded/natural gas)   
5840      Chevrolet       Impala  2017  flex-fuel (unleaded/natural gas)   
6388         Nissan         Leaf  2015                          electric   
6389         Nissan         Leaf  2015                          electric   
6390         Nissan         Leaf  2015                          electric   
6391         Nissan         Leaf  2015                          electric   
6392         Nissan         Leaf  2016                          electric   
6393         Nissan         Leaf  2016                          electric   
6394         Nissan         Leaf  2016                          electric   
6578  Mercedes-Benz      M-Class  2015                            diesel   
6908        Lincoln          MKZ  2017                  regular unleaded   
6910        Lincoln          MKZ  2017                  regular unleaded   
6916        Lincoln          MKZ  2017                  regular unleaded   
6918        Lincoln          MKZ  2017                  regular unleaded   
6925          Tesla      Model S  2015                          electric   
6926          Tesla      Model S  2015                          electric   
6927          Tesla      Model S  2015                          electric   
6928          Tesla      Model S  2015                          electric   
6929          Tesla      Model S  2015                          electric   
6930          Tesla      Model S  2016                          electric   
6931          Tesla      Model S  2016                          electric   
6932          Tesla      Model S  2016                          electric   
6933          Tesla      Model S  2016                          electric   
6934          Tesla      Model S  2016                          electric   
6935          Tesla      Model S  2016                          electric   
6936          Tesla      Model S  2016                          electric   
6937          Tesla      Model S  2016                          electric   
6938          Tesla      Model S  2016                          electric   
9850            Kia      Soul EV  2015                          electric   
9851            Kia      Soul EV  2015                          electric   
9852            Kia      Soul EV  2016                          electric   
9853            Kia      Soul EV  2016                          electric   
9854            Kia      Soul EV  2016                          electric   

      Engine HP  Engine Cylinders Transmission Type      Drive

### Question 5

In [63]:
# Calculate the average "Engine HP" in the dataset.

avg_engineHP = data['Engine HP'].mean()
avg_engineHP

249.38607007176023

In [64]:
print(round(avg_engineHP))

249


In [127]:
# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

data['Engine HP'].fillna(0)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [128]:
# Now, calcualte the average of "Engine HP" again.

newAverage = data['Engine HP'].mean()

In [129]:
print(round(newAverage))

249


### Question 6

In [72]:
# Select all the "Rolls-Royce" cars from the dataset.

dataRollsRoyce = data[data['Make']=='Rolls-Royce']

In [73]:
# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

dataRollsRoyceFilter = dataRollsRoyce[['Engine HP', 'Engine Cylinders', 'highway MPG']]
dataRollsRoyceFilter

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [74]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

dataRollsRoyceDropDuplicates = dataRollsRoyceFilter.drop_duplicates()

In [75]:
dataRollsRoyceDropDuplicates

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [130]:
# Get the underlying NumPy array. Let's call it X.

x = dataRollsRoyceDropDuplicates.values 
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [137]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = x.T.dot(x)

In [138]:
XTX 

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [139]:
XTX_Inv = np.linalg.inv(XTX)
XTX_Inv.sum()

0.032212320677486125

In [140]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [141]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_Inv.dot(x.T).dot(y)

In [142]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

### END